### ISSUE TITLE
Consider sending to actor channel instead of offering

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#15]
_Originally posted by @erikhuizinga in https://github.com/uniflow-kt/uniflow-kt/pull/12#issuecomment-577102092_

Side note for a different issue:
Why are state actions `offer`ed to the actor instead of using `send`? `offer` returns false and the action isn't added to the queue, but `send` suspends the sender until the buffer has capacity again. Why is the latter not an option?

Imagine I'm setting a loading state:

0. `setState { LoadingState }` -> UI shows loading UI
0. `DataFlow` loads data -> data loaded
0. `setState { DataState }` <- oops! The buffer was already full, so the new state was never actually set.
0. Now the UI still is in the loading state, but nothing is loading.

If `send` would be used instead of `offer`, the `setState { DataState }` would eventually set the correct state. This probably has other issues / challenges and maybe you've already considered this. WDYT?

**Comment by erikhuizinga** [comment]
[Slack thread](https://kotlinlang.slack.com/archives/CJF76ENEM/p1579775730002900)

**Comment by arnaudgiuliani** [comment]
Interesting yes, added to `0.10.2`
