### ISSUE TITLE
Restore state against process death

### ISSUE THREAD

**Issue by costular** [uniflow-kt/uniflow-kt#36]
I think a good feature for this library would be a restore state system using SavedStateHandle in order to avoid state loss when the process get killed. It can be done manually but I think it reduces the user's worry about it.

Any thoughts?

**Comment by arnaudgiuliani** [comment]
can be interesting, but this is perhaps linked to the way you use your ViewModel?! 🤔 (SaveState bundle or not)

... but an intersting case to think about :)

**Comment by costular** [comment]
[MvRx](https://github.com/airbnb/MvRx) works like that. You can annotate some State's fields with @PersistState and the library internally will initiate the state recovering that field from `SavedStateHandle`.

I'd give the option to do it, I think it would be great and would cover most of the cases. I haven't thought about the implementation though, it could need a different approach if we make it optional without annotations.

**Comment by arnaudgiuliani** [comment]
yep, clearly have to check a plan for that. Perhaps managing the state at ViiewModel constructor or something. I would like to stay minimal and avoid any extra annotation processing.

**Comment by arnaudgiuliani** [comment]
Perhaps some extensions/help API to manage current state for `SavedStateHandle`

**Comment by arnaudgiuliani** [comment]
I believe this must be a full intentional thing. We can have a `saveState` & `restoreState` functions on Android ViewModels, to let them save/restore the current state to Bundle state.

What do you think @MarcinChrapowicz @erikhuizinga ?

**Comment by erikhuizinga** [comment]
I like the idea of persistable state. I can imagine that after process death, when a certain screen is restored (is this always the launcher activity?), then some state can be restored. Would the view model be the best place for this? Or would some application-global state be a better place for this? Or do you want to leave it up to the user: any `AndroidDataFlow`, when instantiated, can optionally restore a previous state instead of a default state?

**Comment by costular** [comment]
The Android ViewModel with the "new" `SavedStateHandle` is capable of retrieving the saved state or even persist it when process get killed.  

IMO I'd give the option to the user to restore the state using `SavedStateHandle` under the hood instead of setting the default state whenever possible, like [MvRx](https://github.com/airbnb/MvRx) does.

However, there are some things to keep in mind:
- `SavedStateHandle` uses Bundle under the hood so the persistable data should be a primitive, `Parcelable` or `Serializable`
- According to Google a good practice is saving as less as possible. For example, persisting the id and fetching again with that id instead of the full collection. So would be cool to choose which fields should be persisted to avoid persisting collections or another memory consumption.

**Comment by erikhuizinga** [comment]
> * `SavedStateHandle` uses Bundle under the hood so the persistable data should be a primitive, `Parcelable` or `Serializable`

From the UniFlow as a lib point of view I think that it can provide a save-and-restore feature, if the user provides state that is primitive, `Parcelable` or `Serializable`. I don't think it would be a good idea to make all UniFlow `UIData` also either `Parcelable` or `Serializable`. But in other words: this sounds feasible.

> * According to Google a good practice is saving as less as possible. For example, persisting the id and fetching again with that id instead of the full collection. So would be cool to choose which fields should be persisted to avoid persisting collections or another memory consumption.

This sounds like a domain-specific issue: if the user's domain can work with IDs that can be (re)fetched, then the user should build a state machine that works like that, instead of UniFlow providing such behaviour out of the box. Do you agree, or WDYT otherwise? This might be a too narrow use case, although maybe frequently applicable?

**Comment by costular** [comment]
> From the UniFlow as a lib point of view I think that it can provide a save-and-restore feature, if the user provides state that is primitive, Parcelable or Serializable. I don't think it would be a good idea to make all UniFlow UIData also either Parcelable or Serializable. But in other words: this sounds feasible.

Sure, I wasn't suggesting to make all `UIData` Parcelable, just tried to highlight that there's a limitation to implement the feature.

> According to Google a good practice is saving as less as possible. For example, persisting the id and fetching again with that id instead of the full collection. So would be cool to choose which fields should be persisted to avoid persisting collections or another memory consumption.

Same for this point I wasn't suggesting anything related to the id fetching domain usecase, it was just an example to explain why would we need an option to persist only the necessary data instead of the whole UIData` including collections which are memory consumption since Bundle has a memory limit of 1024KB.

**Comment by arnaudgiuliani** [comment]
I clearly agree that we need something explicit, as the user must understand what he tries to save.

Then I would rather propose some function that you can call on your ViewModel. then it would possible to trigger save/restore  from UI or VM itself.

**Comment by marcouberti** [comment]
> is this always the launcher activity?
@erikhuizinga I'm quite sure this is not the case, otherwise the problem would not exist in my opinion.

**Comment by arnaudgiuliani** [comment]
One thing I was wondering is, sometimes in my apps, states can be complex. Would it be ok to store it in those Bundle stuff? 🤔 

not sure.

**Comment by arnaudgiuliani** [comment]
Added `LivePersistentDataPublisher` to help persist state to bundle from ViewModel
