### ISSUE TITLE
Incorrect order of state emissions: default state emitted after other state(s)

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#40]
`AndroidDataFlow.<init>` sets the default state asynchronously:

https://github.com/uniflow-kt/uniflow-kt/blob/38c095e110181a5a565710fc742149bec8eae0de/uniflow-androidx/src/main/java/io/uniflow/androidx/flow/AndroidDataFlow.kt#L55-L57

However, a common use case for me is to extend `AndroidDataFlow` and in my implementation's `init` block I also call `action { setState { someStateThatILoaded } }`. These two actions are _concurrently launched_ in `ActionDispatcher`:

https://github.com/uniflow-kt/uniflow-kt/blob/38c095e110181a5a565710fc742149bec8eae0de/uniflow-core/src/main/kotlin/io/uniflow/core/flow/ActionDispatcher.kt#L22

Remember that `CoroutineScope.launch {}` returns quickly. However, AFAIK _no order of execution is guaranteed_! If the scope is backed by multiple threads, the order of these launched jobs is undefined and therefore 🐛 it is undefined which of the two states is set first!

### User story

As a user I expect the `defaultState` constructor argument to be set as soon as all `AndroidDataFlow<init>` blocks return.

### Suggestion

Do not asynchronously set state in `AndroidDataFlow.<init>`, but instead synchronously set state.

### Workaround

Await `defaultState` and only then start setting your own states. In other words: don't set state from your `AndroidDataFlow` implementation's `init` block.

### Version affected

UniFlow version: 0.11.2

**Comment by arnaudgiuliani** [comment]
Fixed in #41 

thanks @ggajews
