### ISSUE TITLE
Replace LiveData with StateFlow

### ISSUE THREAD

**Issue by arnaudgiuliani** [uniflow-kt/uniflow-kt#44]
Hi,

another proposition is to stop using LiveData for StateFlow. Would avoid such Event<> UIevent wrapper

**Comment by MarcinChrapowicz** [comment]
Hey, 
I'm not sure if this will help to avoid using Event<> wrapper from the documentation we can see that it is always returning value `StateFlow always has a value which can be safely read at any time via value property.`. This wrapper is only to see if you already used/consumed this event 

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-state-flow/

How do you want to avoid Event wrapper?

**Comment by arnaudgiuliani** [comment]
arf, good catch :/

**Comment by arnaudgiuliani** [comment]
it's more than if you have several UI using `take()` on an event ... then it's hiding the event. You need to check that manually. Perhaps, everyone can see the event as consumed with StateFlow ... need to try 🤔

**Comment by arnaudgiuliani** [comment]
finally, it's a "way" to send those data out to the UI. Not a way to solve the Event wrapper problem. I will propose in that way.
