### ISSUE TITLE
Fatal exception in UIState.Failed constructor

### ISSUE THREAD

**Issue by nic-bell** [uniflow-kt/uniflow-kt#46]
With Uniflow `0.11.4` when I `setState` with a message only:

```kotlin
setState(UIState.Failed("Some message here")
```

I get a fatal exception:

Fatal Exception: `kotlin.TypeCastException`
`null` cannot be cast to non-null type `io.uniflow.core.flow.data.UIError`
`io.uniflow.core.flow.data.UIState$Failed.<init>`

I am pretty sure it's be cause of this line where `null` is being cast.

https://github.com/uniflow-kt/uniflow-kt/blob/36d2914e1588470c5f904b5707a463d5802adf45/uniflow-core/src/main/kotlin/io/uniflow/core/flow/data/UIState.kt#L39

**Comment by arnaudgiuliani** [comment]
Hi @nic-bell 

Good catch, yes :)

**Comment by arnaudgiuliani** [comment]
will be pushed in next release
