### ISSUE TITLE
Avoid Print State 

### ISSUE THREAD

**Issue by dommy1985** [uniflow-kt/uniflow-kt#50]
Hi I Wold Like to hide state print , there is a possibility ?

**Comment by arnaudgiuliani** [comment]
Hello, you just need to use the `UniflowLogger` to setup with EmptyLogger

**Comment by dommy1985** [comment]
it cloud be nice is someone upload `0.11.7` on maven repo

**Comment by arnaudgiuliani** [comment]
yep, it's scheduled
