### ISSUE TITLE
Avoid re-send unchanged states

### ISSUE THREAD

**Issue by costular** [uniflow-kt/uniflow-kt#54]
Hi!

I think would be a good idea to use something like `distinctUntilChanged()` in order to avoid repeated states so it keeps away from drawing over and over unnecessarily. 

I'm using this library in production and found that sometimes the re-draw is unnecessary since the state hasn't changed at all.

**Comment by arnaudgiuliani** [comment]
Hi,

you can use `notifyStateUpdate` to update internally a state, and notify it by a simple Event

**Comment by costular** [comment]
It sounds good. However, IMO would be great to update the view only when necessary, I cannot think of any benefit to update the state continuously when it remains the same. Most of the MVI apps I used handle it under the hood using `distinctUntilChanged()` or even Jetpack Compose since there is no point to re-draw the view when the state is the same as before.

**Comment by arnaudgiuliani** [comment]
Interesting, yes 👍

**Comment by arnaudgiuliani** [comment]
Just introduced this in `0.12.0-beta-1` if you can check 👍
