### ISSUE TITLE
Using flow from database

### ISSUE THREAD

**Issue by sedestrian** [uniflow-kt/uniflow-kt#58]
Hi, It's my first time using MVI and i used your library to try and implement it. While doing so i noticed that you can't have a running action and also call other actions at the same time. This happened to me because i want to use a flow from room database as single source of truth and send other actions to update data from api and save to room, or do other stuff. I don't understand if this is a bug or if it's by design, but if it is by design is there no way in MVI to have an ongoing subscription to db data?

**Comment by arnaudgiuliani** [comment]
If I understand your case, you're getting a Flow<T> from your database. 

Best then is to map or collect it and transform each item in an action. It should be ok with your design.
