### ISSUE TITLE
JCenter migration

### ISSUE THREAD

**Issue by arnaudgiuliani** [uniflow-kt/uniflow-kt#59]
Hello,

with the Jcenter sunsetting in a few time, we need to update publication scripts to help publish on maven central.

**Comment by erikhuizinga** [comment]
Here a repo of mine that just migrated from JCenter to Maven Central. You might find some of the build scripts useful: https://github.com/erikhuizinga/mockk-patterns/pull/14 (based on [Sonatype's Gradle docs](https://github.com/erikhuizinga/mockk-patterns/pull/14)).

**Comment by arnaudgiuliani** [comment]
Uniflow is getting deployed on maven central 👍

**Comment by erikhuizinga** [comment]
@arnaudgiuliani will versions before 1.0.0 also be published to maven central?

**Comment by arnaudgiuliani** [comment]
yeah, currently deploying 1.0.0-SNAPSHOT. https://search.maven.org/search?q=org.uniflow-kt

I need to communicate about group id change. It's now `org.uniflow-kt`

**Comment by erikhuizinga** [comment]
I meant older versions like 0.11.6, which appears to be the latest: https://github.com/uniflow-kt/uniflow-kt/releases. Therefore, likely many users will use that version.

**Comment by arnaudgiuliani** [comment]
I can backport the latest old one. It will require group id change. I can't push to `io.uniflow`
