### ISSUE TITLE
Receive events in jetpack compose?

### ISSUE THREAD

**Issue by RinOrz** [uniflow-kt/uniflow-kt#68]
I only saw the `states` but not the `events`. What should I do?

**Comment by arnaudgiuliani** [comment]
For Jetpack compose, just use regular onEvents() with your ViewModel 👍

**Comment by StephanSchuster** [comment]
Maybe something like this (https://github.com/uniflow-kt/uniflow-kt/pull/84) could help with Jetpack Compose.

**Comment by arnaudgiuliani** [comment]
yes, let's continue with your PR then 👍
