### ISSUE TITLE
Give unique or settable names to mocked view observers (mock, mockk)

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#7]
When debugging test code stack traces it helps if you give custom names to mocks.

Currently (Uniflow 0.9.0 with AndroidX), a stack trace might look like this:

```
java.lang.AssertionError: Verification failed: calls are not exactly matching verification sequence

Matchers: 
Observer(#1).onChanged(eq(...)))
```

But since the user does not use `Observer` instances or the `Observer` class (not directly, at least), this can be confusing.

In the code below you don't give custom names to the MockK mocks you create.

**Suggestion:** give custom names to these mocks (e.g. `"Uniflow UIState Observer mock"` and `"Uniflow UIEvent Observer mock"`), or make them settable through an optional argument to `mockObservers` for additional flexibility.

The result would still contain `Observer`s, but would then become something like:

```
java.lang.AssertionError: Verification failed: calls are not exactly matching verification sequence

Matchers: 
Observer(Uniflow UIState Observer mock#1).onChanged(eq(...)))
```

Here the responsible code:

https://github.com/uniflow-kt/uniflow-kt/blob/83fb0191c358258f122fe8e64cb84c3d022146c0/uniflow-androidx-test/src/main/java/io/uniflow/android/test/MockedViewObserver.kt#L16-L17

I can make a PR if you want.

**Comment by arnaudgiuliani** [comment]
is still relevant here @erikhuizinga?

**Comment by erikhuizinga** [comment]
This is not a big issue, but it would be nice to have.

**Comment by arnaudgiuliani** [comment]
Ha ok, didn't read. It's on the Mockk side then

**Comment by arnaudgiuliani** [comment]
It has been added in https://github.com/uniflow-kt/uniflow-kt/commit/06a9e75248e076d737ba58a96d74c7a96f9e1e34
