### ISSUE TITLE
Why is setState deprecated within an action?

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#8]
The following code prevents calling `setState` within `setState`.

https://github.com/uniflow-kt/uniflow-kt/blob/83fb0191c358258f122fe8e64cb84c3d022146c0/uniflow-core/src/main/kotlin/io/uniflow/core/flow/StateAction.kt#L8-L9

Bad code:

```kotlin
// In an AndroidDataFlow

fun foo() {
  setState {
    setState { SomeState } // <- Error!
    AnotherState
  }
}
```

However, I am allowed to do this:

```kotlin
// In an AndroidDataFlow

fun foo() {
  setState { // Outer setState
    bar()
    AnotherState
  }
}

fun bar() {
  setState { SomeState } // Inner setState
}
```

The two examples are not equivalent, because the first erroneous `setState` is a member of `StateAction` (the receiver inside the first lambda), and the `setState` in `bar` is a member of `DataFlow`. The latter is allowed to be called anywhere on a `DataFlow`. The problem is that they seem equivalent and nothing prevents me from doing this.

I wonder if the behaviour is well-defined in my second example. The outer `setState` will run on a coroutine that will update the internal state, but before it does, a new action from the inner `setState` call is scheduled on that same coroutine? When will what action execute? Will I first observe `AnotherState` and then `SomeState` or the other way around?

**Comment by MarcinChrapowicz** [comment]
Hey, there is a reason for that because we want to block a user to have this possibility, but it is hard to block every possible way. We should use setState only when we want to set one state if we want to set a few states we should use `stateFlow`.

**Comment by MarcinChrapowicz** [comment]
Sorry for don't reply directly to your question, but why we want to setState inside another setState ?, There is a reason for that ?

**Comment by erikhuizinga** [comment]
`stateFlow` should be used, yes, but as a user I might simply want to set multiple states in succession and, from my `DataFlow` I can very easily call `setState` multiple times in succession. So it is easy to get it wrong. But why is it wrong?

The use case is the same as the use case for `stateFlow`: set multiple states in succession.

**Comment by erikhuizinga** [comment]
Naively a user would just call `setState` multiple times sequentially, but they might end up nesting these calls indirectly (second example in first post): that's probably an error but nothing prevents them from doing so.

**Comment by MarcinChrapowicz** [comment]
> `stateFlow` should be used, yes, but as a user I might simply want to set multiple states in succession and, from my `DataFlow` I can very easily call `setState` multiple times in succession. So it is easy to get it wrong. But why is it wrong?
> 
> The use case is the same as the use case for `stateFlow`: set multiple states in succession.

**Comment by arnaudgiuliani** [comment]
new action API won't make it suspicious. 

```kotlin
action { 
 setState { }
}
```
