### ISSUE TITLE
Default state isn't emitted in tests

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#86]
(Also reported through the Kotlin language Slack [here](https://kotlinlang.slack.com/archives/CJF76ENEM/p1634585984011000).)

The testing docs (https://github.com/uniflow-kt/uniflow-kt/blob/master/doc/testing.md) suggest that it might be possible to test the default `UIState` of a `DataFlow`. In fact, on UniFlow 0.11.6 the following test passes, but on v1.0.10 it fails! This is unexpected and possibly even a bug! The suggestion is to also emit the default state for testing purposes, as this is likely what the user intends to test.

MWE:

```kotlin
// Imports skipped for brevity, and because they differ for v0.11.6 and v1.0.10

class ADFTest {
    @get:Rule
    val instantTaskExecutorRule = InstantTaskExecutorRule()

    @Test
    fun androidDataFlowEmitsDefaultState() {
        val androidDataFlow = object : AndroidDataFlow(defaultState = UIState.Success) {}
        val testObserver = androidDataFlow.createTestObserver()
        assertEquals(1, testObserver.statesCount)
    }
}
```

**Comment by ggajews** [comment]
If you look at the current implementation https://github.com/uniflow-kt/uniflow-kt/blob/master/uniflow-android/src/main/java/io/uniflow/android/livedata/LiveDataPublisher.kt#L25 default state is just set as `_currentState` but never makes it to the `_states` live data.

**Comment by arnaudgiuliani** [comment]
exact yes, it was the point that the first default state to be set is never emitted. Perhaps is something we could allow to setup. 

@erikhuizinga is it a 1.0.10 only change? then we can revert

**Comment by erikhuizinga** [comment]
I tested the versions affected:

✅ 1.0.4 is the last version that passes the test.
❌ 1.0.5 is the first version that fails the test.

Either revert the change or make the states live data emit the initial state, which is for the observer to handle.
Or document it very clearly that the initial state is just internal, and never emitted.
Then this issue can be closed.

I would say that always emitting the initial state is logical, because what's the use otherwise?

**Comment by arnaudgiuliani** [comment]
> I would say that always emitting the initial state is logical, because what's the use otherwise?

yes clearly. @MarcinChrapowicz any thought on that?

**Comment by arnaudgiuliani** [comment]
Ok, let's go for this then 👍 @MarcinChrapowicz will tell us if needed
