### ISSUE TITLE
Action.onError is called twice if it throws an exception

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#87]
UniFlow 1.0.10 calls `Action.onError` twice for error functions that throw an exception. The default `onError` function for data flows throws an exception, defined here: https://github.com/uniflow-kt/uniflow-kt/blob/1.0.10/uniflow-core/src/main/kotlin/io/uniflow/core/flow/DataFlow.kt#L42-L45. So, the default behaviour is that the error function is run twice.

Likely, this is caused by `actionOn<T : UIState> {}` being reduced by https://github.com/uniflow-kt/uniflow-kt/blob/1.0.10/uniflow-core/src/main/kotlin/io/uniflow/core/flow/ActionReducer.kt#L50-L62. This code calls `action.onError` twice, because:

1. The state isn't the target state: 👍.
2. The `BadOrWrongStateException` is thrown by the first `onError` call, which is caught by `catch (e: Exception)` which runs `onError` again: 👎.

The MWE below simply tests that the default `onError` function is called twice, because the default function logs a message. The test simply counts the logged error messages. There should be exactly one, but there are two. This is by no means a good test for this issue, but it simply demonstrates the issue.

MWE (deps: JUnit 4.13.2, UniFlow 1.0.10):

```kotlin
import io.uniflow.android.AndroidDataFlow
import io.uniflow.core.flow.actionOn
import io.uniflow.core.flow.data.UIEvent
import io.uniflow.core.flow.data.UIState
import io.uniflow.core.logger.Logger
import io.uniflow.core.logger.UniFlowLogger
import io.uniflow.test.rule.UniflowTestDispatchersRule
import kotlin.test.assertEquals
import kotlinx.coroutines.test.TestCoroutineDispatcher
import org.junit.Rule
import org.junit.Test

class SingleLogTest {
    companion object {
        private val testCoroutineDispatcher = TestCoroutineDispatcher()
    }

    @get:Rule
    val uniflowTestDispatchersRule = UniflowTestDispatchersRule(testCoroutineDispatcher)

    @Test
    fun `bad or wrong state is logged once`() {
        val logger = object : Logger {
            val messages = mutableListOf<String>()

            override fun debug(message: String) {
            }

            override fun log(message: String) {
            }

            override fun logError(errorMessage: String, error: Exception?) {
                messages += errorMessage
                println(errorMessage)
            }

            override fun logEvent(event: UIEvent) {
            }

            override fun logState(state: UIState) {
            }
        }

        UniFlowLogger.init(logger)

        val androidDataFlow = object : AndroidDataFlow(defaultState = UIState.Empty) {
            fun foo() = actionOn<UIState.Loading> {}
        }

        androidDataFlow.foo() // Should log an uncaught error about a BadOrWrongStateException

        assertEquals(1, logger.messages.size)
    }
}
```

Fails with

```
expected:<1> but was:<2>
Expected :1
Actual   :2
```

**Comment by erikhuizinga** [comment]
Also, shouldn't the following test function fail with an exception, i.e. the `BadOrWrongStateException`?

```kotlin
class FailsWithBadOrWrongStateExceptionTest {
    companion object {
        private val testCoroutineDispatcher = TestCoroutineDispatcher()
    }

    @get:Rule
    val uniflowTestDispatchersRule = UniflowTestDispatchersRule(testCoroutineDispatcher)

    @Test
    fun `actionOn wrong state fails with BadOrWrongStateException`() {
        assertFailsWith<BadOrWrongStateException> {
            testCoroutineDispatcher.runBlockingTest {
                object : AndroidDataFlow(defaultState = UIState.Empty) {
                    init {
                        actionOn<UIState.Loading> {}
                    }
                }
            }
        }
    }
}
```

Instead, the exception isn't thrown by `runBlockingTest` and therefore the assertion fails.

**Comment by arnaudgiuliani** [comment]
On your first test, we can see that the error is thrown twice on the dataFlow `onError` function: 

![image](https://user-images.githubusercontent.com/2360688/145174606-b8465efa-f7b3-4a87-98e3-a511090fd210.png)

With the following stack if we add debug logs message:
![image](https://user-images.githubusercontent.com/2360688/145174659-c76d38f3-0a65-4d92-a6cb-4a033e54ae49.png)

Fix would consist in catch the `BadOrWrongStateException` to log it, but not throw it

![image](https://user-images.githubusercontent.com/2360688/145175025-03a29ec5-7823-4e6e-87ae-83858a7b4b99.png)

test is then passing: 
![image](https://user-images.githubusercontent.com/2360688/145175080-f631c286-dde1-4b11-b265-2ea1e825dd8b.png)

I push the PR 👍
