### ISSUE TITLE
saferesult artifact is missing from documentation

### ISSUE THREAD

**Issue by erikhuizinga** [uniflow-kt/uniflow-kt#9]
`implementation "io.uniflow:uniflow-saferesult:$version"` is missing from any documentation, but it is required to use the `SafeResult` feature.

**Comment by MarcinChrapowicz** [comment]
We will take a look at the documentation, Thanks 👍

**Comment by arnaudgiuliani** [comment]
I'm seperating Functional documentation from main core/container

**Comment by arnaudgiuliani** [comment]
I will add more content from Arrow, then trying to maintain this SafeResult classes
