### ISSUE TITLE
Restore state doesn't update state in base class

### ISSUE THREAD

**Issue by nicbell** [uniflow-kt/uniflow-kt#90]
Restore state doesn't update state value stored in `LiveDataPublisher`.

https://github.com/uniflow-kt/uniflow-kt/blob/32094d0951afa323de1c9f9be43fcf265cf43103/uniflow-android/src/main/java/io/uniflow/android/livedata/PersistentLiveDataPublisher.kt#L18

`PersistentLiveDataPublisher.restoreState` updates `_states` object but `_currentState` in `LiveDataPublisher ` never gets updated on restore.

This means `states.value` will have the correct value in your view model but `getState()` will be incorrect.

**Comment by arnaudgiuliani** [comment]
Good catch

**Comment by arnaudgiuliani** [comment]
has been merged for 1.1.1
