### ISSUE TITLE
Could not find uniflow-android-1.1.1.aar

### ISSUE THREAD

**Issue by frapontillo** [uniflow-kt/uniflow-kt#92]
Hello, I am trying to update to 1.1.1 but it looks like the `aar` isn't published on Maven: https://repo.maven.apache.org/maven2/org/uniflow-kt/uniflow-android/1.1.1/

**Comment by arnaudgiuliani** [comment]
let me check 🤔

**Comment by RicardoRSousa** [comment]
hey @arnaudgiuliani, any update on this? 🤔
Thank you!

**Comment by arnaudgiuliani** [comment]
not yet, Need perhaps to ask some config update changes at Maven central 🤔

**Comment by arnaudgiuliani** [comment]
I'm reupdating for 1.1.2 then
